apiVersion: v1
kind: Pod
metadata:
  name: fiapapipod
  labels:
    app: fiapapipod
spec:
  containers:
  - name: fiapapipod
    image: drungas/drungas-api-teste:latest
    ports:
    - containerPort: 8080
  