name: CI/CD Pipeline Test API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: docker build -t drungas/drungas-api-teste:latest . && docker push drungas/drungas-api-teste:latest
      
      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_NEW }}
          version: 1.21.0

      - name: Deploy to AKS
        run: kubectl apply -f FiapApIDocker/YAMLS/deployment.yml

      - name: Restart
        run: kubectl rollout restart deployment fiapapipod


      - name: Esperar a implantação concluir
        run: kubectl wait --for=condition=available deployment/fiapapipod

